using GTRC_Basics;
using GTRC_Database_Client.Responses;
using GTRC_Basics.Models;

namespace GTRC_Database_Client.Requests
{
    public class DbApiRequestEntry(DbApiConnectionConfig? connection = null) : DbApiRequest<Entry>(connection)
    {
        public async Task<DbApiListResponse<Entry>> GetAutoGeneratedRaceNumbers(int seasonId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Get, "/AutoGeneratedRaceNumbers/" + seasonId.ToString()); }
            return await ReturnAsList(Response);
        }

        public async Task<DbApiListResponse<Entry>> UpdateRaceNumbers(int seasonId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Update, "/RaceNumbers/" + seasonId.ToString()); }
            return await ReturnAsList(Response);
        }

        public async Task<DbApiListResponse<Entry>> GetByUserSeason(int userId, int seasonId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Get, "/ByUserSeason/" + userId.ToString() + "/" + seasonId.ToString()); }
            return await ReturnAsList(Response);
        }

        public async Task<DbApiListResponse<Entry>> GetByUserEvent(int userId, int eventId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Get, "/ByUserEvent/" + userId.ToString() + "/" + eventId.ToString()); }
            return await ReturnAsList(Response);
        }

        public async Task<DbApiValueResponse<byte>> GetCarChangeCount(int entryId, int eventId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Get, "/CarChangeCount/" + entryId.ToString() + "/" + eventId.ToString()); }
            return new DbApiValueResponse<byte>(Response);
        }
    }
}
