using GTRC_Basics;
using GTRC_Database_Client.Responses;
using GTRC_Basics.Models;

namespace GTRC_Database_Client.Requests
{
    public class DbApiRequestEntry(DbApiConnectionConfig? connection = null) : DbApiRequest<Entry>(connection)
    {
        public async Task<DbApiListResponse<Entry>> GetAutoGeneratedRaceNumbers(int seasonId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Get, "/AutoGeneratedRaceNumbers/" + seasonId.ToString()); }
            return await ReturnAsList(Response);
        }

        public async Task<DbApiListResponse<Entry>> UpdateRaceNumbers(int seasonId)
        {
            if (connection is not null) { Response = await connection.SendRequest(Model, HttpRequestType.Update, "/RaceNumbers/" + seasonId.ToString()); }
            return await ReturnAsList(Response);
        }
    }
}
